ByteWriter/Controllers/ArticleController.cs
using ByteWriter.Models;
using ByteWriter.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace ByteWriter.Controllers
{
    [Authorize]
    public class ArticleController : Controller
    {
        private readonly IArticleService _articleService;
        private readonly UserManager<User> _userManager;

        public ArticleController(IArticleService articleService, UserManager<User> userManager)
        {
            _articleService = articleService;
            _userManager = userManager;
        }

        // GET: Article
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null)
            {
                return NotFound();
            }

            var articles = await _articleService.FindByUserIdAsync(currentUser.Id);
            return View(articles);
        }

        // GET: Article/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Article/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Article article)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null)
            {
                return NotFound();
            }

            currentUser = await _userManager.Users
                .Include(u => u.Blog)
                .FirstOrDefaultAsync(u => u.Id == currentUser.Id);

            if (currentUser.Blog == null)
            {
                return BadRequest("User doesn't have a blog.");
            }

            article.ArticleTimestamp = DateTime.UtcNow;
            _articleService.Create(article);

            var blog = currentUser.Blog;
            blog.Articles.Add(article);

            _articleService.Save();

            return RedirectToAction(nameof(Index));
        }

        // GET: Article/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _articleService.FindByCondition(a => a.ArticleID == id).FirstOrDefaultAsync();
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        // POST: Article/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var article = await _articleService.FindByCondition(a => a.ArticleID == id).FirstOrDefaultAsync();

            if (article == null)
            {
                return NotFound();
            }

            var currentUser = await _userManager.GetUserAsync(User);

            _articleService.Delete(article);
            _articleService.Save();
            return RedirectToAction(nameof(Index));
        }


        private bool ArticleExists(int id)
        {
            return _articleService.FindByCondition(a => a.ArticleID == id).FirstOrDefault() != null;
        }
    }
}

ByteWriter/Controllers/FriendBlogController.cs
using ByteWriter.Models;
using ByteWriter.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace ByteWriter.Controllers
{
    [Authorize]
    public class FriendBlogController : Controller
    {
        private readonly IFriendBlogService _friendBlogService;
        private readonly UserManager<User> _userManager;

        public FriendBlogController(IFriendBlogService friendBlogService, UserManager<User> userManager)
        {
            _friendBlogService = friendBlogService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser != null)
            {
                var friendsBlogs = await _friendBlogService.GetFriendsBlogs(currentUser.Id);
                return View(friendsBlogs);
            }
            return Forbid();
        }

    }
}

ByteWriter/Controllers/TrendingBlogController.cs
using ByteWriter.Models;
using ByteWriter.Models.ViewModels;
using ByteWriter.Services;
using ByteWriter.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace ByteWriter.Controllers
{
    public class TrendingBlogController : Controller
    {
        private readonly ITrendingBlogService _trendingBlogService;
        private readonly IUserService _userService;
        private readonly IBlogService _blogService;

        public TrendingBlogController(ITrendingBlogService trendingBlogService, IUserService userService, IBlogService blogService)
        {
            _trendingBlogService = trendingBlogService;
            _userService = userService;
            _blogService = blogService;
        }

        public async Task<IActionResult> Index()
        {
            var trendingBlogs = _trendingBlogService.GetTrendingBlogs();
            var blogs = new List<Blog>();

            foreach (var trendingBlog in trendingBlogs)
            {
                var blog = await _blogService.FindByCondition(b => b.BlogID == trendingBlog.BlogId)
                                              .FirstOrDefaultAsync();
                if (blog != null)
                {
                    blogs.Add(blog);
                }
            }

            var blogUsers = new Dictionary<int, List<User>>();

            foreach (var blog in blogs)
            {
                var users = await _userService.FindByCondition(u => u.BlogId == blog.BlogID)
                                              .ToListAsync();
                blogUsers[blog.BlogID] = users.ToList();
            }

            var viewModel = new BlogWithUsersViewModel
            {
                Blogs = blogs,
                BlogUsers = blogUsers
            };

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> SelectTrending()
        {
            var model = new SelectTrendingViewModel();

            var blogs = await _blogService.FindAll().ToListAsync();
            model.Blogs = blogs;

            var trendingBlogs = _trendingBlogService.GetTrendingBlogs().Select(tb => tb.BlogId).ToList();
            model.SelectedBlogIds = trendingBlogs;

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SelectTrending(SelectTrendingViewModel model)
        {
            var allTrending = _trendingBlogService.GetTrendingBlogs().Select(tb => tb.BlogId).ToList();

            foreach (var blogId in model.SelectedBlogIds)
            {
                if (!allTrending.Contains(blogId))
                {
                    _trendingBlogService.AddTrendingBlog(blogId);
                }
            }

            foreach (var blogId in allTrending)
            {
                if (!model.SelectedBlogIds.Contains(blogId))
                {
                    _trendingBlogService.RemoveTrendingBlog(blogId);
                }
            }

            return RedirectToAction(nameof(Index));
        }
        

    }
}

ByteWriter/Controllers/UserController.cs
using ByteWriter.Models;
using ByteWriter.Models.ViewModels;
using ByteWriter.Services.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace ByteWriter.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IArticleService _articleService;
        private readonly IBlogService _blogService;

        public UserController(UserManager<User> userManager, IArticleService articleService, IBlogService blogService)
        {
            _userManager = userManager;
            _articleService = articleService;
            _blogService = blogService;
        }

        [HttpGet]
        public async Task<IActionResult> Search(string query)
        {
            if (string.IsNullOrEmpty(query))
            {
                return View(new List<UserSearchViewModel>());
            }

            var users = await _userManager.Users
                .Where(u => u.UserName.StartsWith(query))
                .ToListAsync();

            var currentUser = await _userManager.GetUserAsync(User);
            var searchResults = users.Select(u => new UserSearchViewModel
            {
                UserName = u.UserName.Split('@')[0],
                Email = u.Email,
                Bio = u.Bio,
                IsFollowing = currentUser?.Following?.Any(f => f.Id == u.Id) ?? false,
                UserId = u.Id,
                IsCurrentUser = currentUser?.Id == u.Id
            }).ToList();

            return View(searchResults);
        }

        [HttpGet("Profile")]
        public async Task<IActionResult> Profile()
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return RedirectToAction("Login", "Account");
            }

            return RedirectToAction("Profile", new { username = user.UserName });
        }

        [HttpGet("Profile/{username}")]
        public async Task<IActionResult> Profile(string username)
        {
            var user = await _userManager.FindByNameAsync(username);

            if (user == null)
            {
                return RedirectToAction("Login", "Account");
            }

            var currentUser = await _userManager.GetUserAsync(User);

            bool isFollowing = currentUser?.Following?.Any(f => f.Id == user.Id) ?? false;

            var viewModel = new UserProfileViewModel
            {
                UserName = user.UserName.Split('@')[0],
                Email = user.Email,
                Bio = user.Bio,
                IsAdministrator = await _userManager.IsInRoleAsync(user, "Administrator"),
                StatusMessage = TempData["StatusMessage"] as string,
                IsFollowing = isFollowing,
                IsCurrentUser = currentUser?.Id == user.Id,
                UserId = user.Id
            };

            if (user.BlogId.HasValue)
            {
                var articles = await _articleService.FindByBlogIdAsync(user.BlogId.Value);
                viewModel.UserArticles = articles;
            }
            else
            {
                viewModel.UserArticles = new List<Article>();
            }

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Follow(string userId)
        {
            var currentUser = await _userManager.GetUserAsync(User);

            if (currentUser == null || currentUser.Id == userId)
            {
                return RedirectToAction("Index");
            }

            var userToFollow = await _userManager.FindByIdAsync(userId);

            if (userToFollow == null)
            {
                return RedirectToAction("Index");
            }

            currentUser.Following.Add(userToFollow);

            await _userManager.UpdateAsync(userToFollow);

            return RedirectToAction("Profile", new { username = userToFollow.UserName });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Unfollow(string userId)
        {
            var currentUser = await _userManager.GetUserAsync(User);

            if (currentUser == null || currentUser.Id == userId)
            {
                return RedirectToAction("Index");
            }

            var userToUnfollow = await _userManager.FindByIdAsync(userId);

            if (userToUnfollow == null)
            {
                return RedirectToAction("Index");
            }

            currentUser.Following.Remove(userToUnfollow);

            await _userManager.UpdateAsync(userToUnfollow);

            return RedirectToAction("Profile", new { username = userToUnfollow.UserName });
        }


        [HttpGet]
        public async Task<IActionResult> Edit()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound();
            }

            var model = new EditBioViewModel { Bio = user.Bio };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditBioViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);
                if (user == null)
                {
                    return NotFound();
                }

                user.Bio = model.Bio;
                var result = await _userManager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    TempData["StatusMessage"] = "Bio updated successfully!";
                    return RedirectToAction("Profile");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var article = await _articleService.FindByCondition(a => a.ArticleID == id).FirstOrDefaultAsync();
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        [HttpGet]
        public async Task<IActionResult> Friends()
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return null;
            }

            var allUsers = await _userManager.Users.ToListAsync();

            var followers = allUsers.Where(u => u.Following.Contains(user));
            var following = user.Following;

            var friends = followers.Where(u => following.Contains(u)).ToList();

            return View(friends);
        }

    }
}

ByteWriter/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using ByteWriter.Models

@inject SignInManager<User> SignInManager
    @inject UserManager<User> UserManager

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ByteWriter</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ByteWriter.styles.css" asp-append-version="true" />
    <link rel="icon" type="image/x-icon" href="~/favicon.ico">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
            <div class="container-fluid mx-3">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ByteWriter</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto mt-2 mt-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" asp-area="" asp-controller="Home"
                               asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" asp-area="" asp-controller="Article"
                               asp-action="Index">Create!</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" asp-area="" asp-controller="" asp-action=""
                               id="dropdownId" data-bs-toggle="dropdown" aria-haspopup="true"
                               aria-expanded="false">Explore</a>
                            <div class="dropdown-menu" aria-labelledby="dropdownId">
                                <a class="dropdown-item" asp-area="" asp-controller="Home"
                                   asp-action="Explore">Explore Page</a>
                                <a class="dropdown-item" asp-area="" asp-controller="TrendingBlog"
                                   asp-action="Index">Trending Blogs</a>
                                @if (SignInManager.IsSignedIn(User))
                                {

                                    <a class="dropdown-item" asp-area="" asp-controller="FriendBlog" asp-action="Index">Friends' Blogs</a>

                                }
                            </div>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="User" asp-action="Search">Search Users</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <a class="nav-link" asp-area="" asp-controller="User" asp-action="Friends">
                                Friends
                            </a>
                            var currentUserName = User.Identity.Name;
                            <li class="nav-item d-flex align-items-center">
                                <a class="nav-link" asp-area="" asp-controller="User" asp-action="Profile"
                                   asp-route-username="@currentUserName">
                                    Profile <span class="rounded bg-primary px-2 text-dark py-1"> @currentUserName</span>
                                </a>
                            </li>


                        }
                        <partial name="_LoginPartial" />
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container mt-3">
        <main role="main" class="py-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            <div class="py-3 my-3">
                <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="FAQ">FAQs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Features">Features</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">About</a>
                    </li>
                </ul>
                <p class="text-center text-body-secondary h6">
                    © 2024 ByteWriter, Inc.<br>All rights reserved.
                </p>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>